export const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_CURRENT_USER_LOGIN: 'SET_CURRENT_USER_LOGIN',
    SET_CURRENT_USER_LOGOUT: 'SET_CURRENT_USER_LOGOUT',
    SET_CURRENT_USER_ERR: 'SET_CURRENT_USER_ERR',
}
